package com.net2plan.research.niw.networkModel;

class ExcelImporterConstants
{
	enum EXCELSHEETS 
	{ 
		NODES ("Nodes"), FIBERS ("Fibers"), USERSERVICES("UserServices"), VNFTYPES ("VnfTypes") , PERNODEANDSERVICETIMETRAFFIC("PerNodeAndServiceTimeIntensity");  
		private final String tabName; 
		private EXCELSHEETS (String tabName) { this.tabName = tabName; }
		public String getTabName () { return tabName;}
	}
	enum COLUMNS_NODESTAB 
	{
		NODEUNIQUENAME, 
		POSITIONLONGITUDE_DEGREEES, 
		POSITIONLATITUDE_DEGREES,
		NODETYPESTRING,
		ISCONNECTEDTOCORENODE, 
		NODEBASEPOPULATION,
		TOTALNUMCPUS,
		TOTALRAM_GB,
		TOTALHD_GB,
		ARBITRARYPARAMS;  
	}
	
	enum COLUMNS_FIBERSTAB
	{
		ORIGINNODEUNIQUENAME, 
		DESTINATIONNODEUNIQUENAME,
		LENGTH_KM,
		ISBIDIRECTIONAL, 
		VALIDOPTICALSLOTRANGES,
		FIBERATTENUATIONCOEFFICIENT_DBPERKM,
		FIBERCHROMATICDISPERSIONCOEFFICIENT_PSPERNMPERKM,
		FIBERLINKDESIGNVALUEPMD_PSPERSQRKM,
		AMPLIFIERSPOSITIONFROMORIGIN_KM,
		AMPLIFIERGAINS_DB,
		AMPLIFIERNOISEFACTOR_DB,
		AMPLIFIERPMD_PS,
		ARBITRARYPARAMS;  
	}

	enum COLUMNS_VNFTYPES
	{
		VNFTYPEUNIQUENAME, 
		VNFINSTANCECAPACITY_GBPS, 
		OCCUPCPU,
		OCCUPRAM_GB,
		OCCUPHD_GB,
		PROCESSINGTIME_MS,
		ISCONSTRAINEDITSPLACEMENTTOSOMENODES, 
		LISTUNIQUENODENAMESOFNODESVALIDFORINSTANTIATION, 
		ARBITRARYPARAMS;  
	}

	enum COLUMNS_USERSERVICES
	{
		UNIQUEIDSTRING, 
		LISTVNFTYPESCOMMASEPARATED_UPSTREAM, 
		LISTVNFTYPESCOMMASEPARATED_DOWNSTREAM,
		SEQUENCETRAFFICEXPANSIONFACTORRESPECTTOINITIAL_UPSTREAM,
		SEQUENCETRAFFICEXPANSIONFACTORRESPECTTOINITIAL_DOWNSTREAM,
		LISTMAXLATENCYFROMINITIALTOVNFSTART_MS_UPSTREAM, 
		LISTMAXLATENCYFROMINITIALTOVNFSTART_MS_DOWNSTREAM, 
		INJECTIONDOWNSTREAMEXPANSIONFACTORRESPECTTOINITIALUPSTREAM,
		ISENDINGINCORENODE,
		ARBITRARYPARAMS;  
	}

	enum COLUMNS_PERNODEANDSERVICETIMEINTENSITYGBPS
	{
		INJECTIONNODEUIQUENAME, 
		USERSERVICEUNIQUEID;  
	}
	
}
